# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PyTacToeGame.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_PyTacToeGame(object):
    def setupUi(self, PyTacToeGame):
        if not PyTacToeGame.objectName():
            PyTacToeGame.setObjectName(u"PyTacToeGame")
        PyTacToeGame.setWindowModality(Qt.ApplicationModal)
        PyTacToeGame.resize(480, 640)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PyTacToeGame.sizePolicy().hasHeightForWidth())
        PyTacToeGame.setSizePolicy(sizePolicy)
        PyTacToeGame.setMinimumSize(QSize(480, 640))
        PyTacToeGame.setMaximumSize(QSize(480, 640))
        self.gameSquare00 = QPushButton(PyTacToeGame)
        self.gameSquare00.setObjectName(u"gameSquare00")
        self.gameSquare00.setEnabled(False)
        self.gameSquare00.setGeometry(QRect(30, 30, 120, 120))
        sizePolicy.setHeightForWidth(self.gameSquare00.sizePolicy().hasHeightForWidth())
        self.gameSquare00.setSizePolicy(sizePolicy)
        self.gameSquare00.setMinimumSize(QSize(120, 120))
        self.gameSquare00.setMaximumSize(QSize(120, 120))
        self.gameSquare00.setBaseSize(QSize(120, 120))
        font = QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.gameSquare00.setFont(font)
        self.gameSquare01 = QPushButton(PyTacToeGame)
        self.gameSquare01.setObjectName(u"gameSquare01")
        self.gameSquare01.setEnabled(False)
        self.gameSquare01.setGeometry(QRect(180, 30, 120, 120))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(120)
        sizePolicy1.setVerticalStretch(120)
        sizePolicy1.setHeightForWidth(self.gameSquare01.sizePolicy().hasHeightForWidth())
        self.gameSquare01.setSizePolicy(sizePolicy1)
        self.gameSquare01.setMinimumSize(QSize(120, 120))
        self.gameSquare01.setMaximumSize(QSize(120, 120))
        self.gameSquare01.setBaseSize(QSize(120, 120))
        self.gameSquare01.setFont(font)
        self.gameSquare02 = QPushButton(PyTacToeGame)
        self.gameSquare02.setObjectName(u"gameSquare02")
        self.gameSquare02.setEnabled(False)
        self.gameSquare02.setGeometry(QRect(330, 30, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare02.sizePolicy().hasHeightForWidth())
        self.gameSquare02.setSizePolicy(sizePolicy1)
        self.gameSquare02.setMinimumSize(QSize(120, 120))
        self.gameSquare02.setMaximumSize(QSize(120, 120))
        self.gameSquare02.setBaseSize(QSize(120, 120))
        self.gameSquare02.setFont(font)
        self.gameSquare10 = QPushButton(PyTacToeGame)
        self.gameSquare10.setObjectName(u"gameSquare10")
        self.gameSquare10.setEnabled(False)
        self.gameSquare10.setGeometry(QRect(30, 180, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare10.sizePolicy().hasHeightForWidth())
        self.gameSquare10.setSizePolicy(sizePolicy1)
        self.gameSquare10.setMinimumSize(QSize(120, 120))
        self.gameSquare10.setMaximumSize(QSize(120, 120))
        self.gameSquare10.setBaseSize(QSize(120, 120))
        self.gameSquare10.setFont(font)
        self.gameSquare11 = QPushButton(PyTacToeGame)
        self.gameSquare11.setObjectName(u"gameSquare11")
        self.gameSquare11.setEnabled(False)
        self.gameSquare11.setGeometry(QRect(180, 180, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare11.sizePolicy().hasHeightForWidth())
        self.gameSquare11.setSizePolicy(sizePolicy1)
        self.gameSquare11.setMinimumSize(QSize(120, 120))
        self.gameSquare11.setMaximumSize(QSize(120, 120))
        self.gameSquare11.setBaseSize(QSize(120, 120))
        self.gameSquare11.setFont(font)
        self.gameSquare12 = QPushButton(PyTacToeGame)
        self.gameSquare12.setObjectName(u"gameSquare12")
        self.gameSquare12.setEnabled(False)
        self.gameSquare12.setGeometry(QRect(330, 180, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare12.sizePolicy().hasHeightForWidth())
        self.gameSquare12.setSizePolicy(sizePolicy1)
        self.gameSquare12.setMinimumSize(QSize(120, 120))
        self.gameSquare12.setMaximumSize(QSize(120, 120))
        self.gameSquare12.setBaseSize(QSize(120, 120))
        self.gameSquare12.setFont(font)
        self.gameSquare20 = QPushButton(PyTacToeGame)
        self.gameSquare20.setObjectName(u"gameSquare20")
        self.gameSquare20.setEnabled(False)
        self.gameSquare20.setGeometry(QRect(30, 330, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare20.sizePolicy().hasHeightForWidth())
        self.gameSquare20.setSizePolicy(sizePolicy1)
        self.gameSquare20.setMinimumSize(QSize(120, 120))
        self.gameSquare20.setMaximumSize(QSize(120, 120))
        self.gameSquare20.setBaseSize(QSize(120, 120))
        self.gameSquare20.setFont(font)
        self.gameSquare21 = QPushButton(PyTacToeGame)
        self.gameSquare21.setObjectName(u"gameSquare21")
        self.gameSquare21.setEnabled(False)
        self.gameSquare21.setGeometry(QRect(180, 330, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare21.sizePolicy().hasHeightForWidth())
        self.gameSquare21.setSizePolicy(sizePolicy1)
        self.gameSquare21.setMinimumSize(QSize(120, 120))
        self.gameSquare21.setMaximumSize(QSize(120, 120))
        self.gameSquare21.setBaseSize(QSize(120, 120))
        self.gameSquare21.setFont(font)
        self.gameSquare22 = QPushButton(PyTacToeGame)
        self.gameSquare22.setObjectName(u"gameSquare22")
        self.gameSquare22.setEnabled(False)
        self.gameSquare22.setGeometry(QRect(330, 330, 120, 120))
        sizePolicy1.setHeightForWidth(self.gameSquare22.sizePolicy().hasHeightForWidth())
        self.gameSquare22.setSizePolicy(sizePolicy1)
        self.gameSquare22.setMinimumSize(QSize(120, 120))
        self.gameSquare22.setMaximumSize(QSize(120, 120))
        self.gameSquare22.setBaseSize(QSize(120, 120))
        self.gameSquare22.setFont(font)
        self.playerOneNameLabel = QLabel(PyTacToeGame)
        self.playerOneNameLabel.setObjectName(u"playerOneNameLabel")
        self.playerOneNameLabel.setGeometry(QRect(30, 480, 150, 60))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.playerOneNameLabel.setFont(font1)
        self.playerOneNameLabel.setAlignment(Qt.AlignCenter)
        self.gameStartStopButton = QPushButton(PyTacToeGame)
        self.gameStartStopButton.setObjectName(u"gameStartStopButton")
        self.gameStartStopButton.setGeometry(QRect(30, 560, 420, 60))
        self.gameStartStopButton.setFont(font1)
        self.playerSwap = QPushButton(PyTacToeGame)
        self.playerSwap.setObjectName(u"playerSwap")
        self.playerSwap.setGeometry(QRect(210, 480, 60, 60))
        self.playerSwap.setFont(font1)
        self.enemySelect = QComboBox(PyTacToeGame)
        self.enemySelect.addItem("")
        self.enemySelect.addItem("")
        self.enemySelect.addItem("")
        self.enemySelect.setObjectName(u"enemySelect")
        self.enemySelect.setGeometry(QRect(300, 480, 150, 60))
        self.enemySelect.setFont(font1)
        self.enemySelect.setEditable(False)
        self.enemySelect.setMaxVisibleItems(3)
        self.enemySelect.setIconSize(QSize(16, 16))

        self.retranslateUi(PyTacToeGame)

        self.enemySelect.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(PyTacToeGame)
    # setupUi

    def retranslateUi(self, PyTacToeGame):
        PyTacToeGame.setWindowTitle(QCoreApplication.translate("PyTacToeGame", u"PyTacToe", None))
        self.gameSquare00.setText(QCoreApplication.translate("PyTacToeGame", u"P", None))
        self.gameSquare01.setText(QCoreApplication.translate("PyTacToeGame", u"y", None))
        self.gameSquare02.setText("")
        self.gameSquare10.setText(QCoreApplication.translate("PyTacToeGame", u"T", None))
        self.gameSquare11.setText(QCoreApplication.translate("PyTacToeGame", u"a", None))
        self.gameSquare12.setText(QCoreApplication.translate("PyTacToeGame", u"c", None))
        self.gameSquare20.setText(QCoreApplication.translate("PyTacToeGame", u"T", None))
        self.gameSquare21.setText(QCoreApplication.translate("PyTacToeGame", u"o", None))
        self.gameSquare22.setText(QCoreApplication.translate("PyTacToeGame", u"e", None))
        self.playerOneNameLabel.setText(QCoreApplication.translate("PyTacToeGame", u"You", None))
        self.gameStartStopButton.setText(QCoreApplication.translate("PyTacToeGame", u"Start", None))
#if QT_CONFIG(tooltip)
        self.playerSwap.setToolTip(QCoreApplication.translate("PyTacToeGame", u"Swap Players", None))
#endif // QT_CONFIG(tooltip)
        self.playerSwap.setText(QCoreApplication.translate("PyTacToeGame", u"\u2b0c", None))
        self.enemySelect.setItemText(0, QCoreApplication.translate("PyTacToeGame", u"  Easy", None))
        self.enemySelect.setItemText(1, QCoreApplication.translate("PyTacToeGame", u"  Medium", None))
        self.enemySelect.setItemText(2, QCoreApplication.translate("PyTacToeGame", u"  Hard", None))

#if QT_CONFIG(tooltip)
        self.enemySelect.setToolTip(QCoreApplication.translate("PyTacToeGame", u"Select Enemy Level", None))
#endif // QT_CONFIG(tooltip)
        self.enemySelect.setCurrentText(QCoreApplication.translate("PyTacToeGame", u"  Medium", None))
    # retranslateUi

